import type { MailboxConnection, MailboxGroup, MailboxTreeItem, MailboxThreadDetail, MailboxAdminSummary, MailboxPermissionPolicy } from "./types";

export const MOCK_CONNECTIONS: MailboxConnection[] = [
  {
    id: "conn_billing",
    orgId: "org_1",
    provider: "gmail",
    slug: "billing",
    emailAddress: "billing@acmecorp.com",
    displayName: "Billing",
    status: "connected",
    lastSyncAt: "2026-05-08T14:30:00Z",
    lastSyncError: null,
    lastSyncErrorCategory: null,
    unreadCount: 14,
    inboxCount: 47,
  },
  {
    id: "conn_support",
    orgId: "org_1",
    provider: "gmail",
    slug: "support",
    emailAddress: "support@acmecorp.com",
    displayName: "Support",
    status: "connected",
    lastSyncAt: "2026-05-08T14:28:00Z",
    lastSyncError: null,
    lastSyncErrorCategory: null,
    unreadCount: 6,
    inboxCount: 23,
  },
  {
    id: "conn_accounts",
    orgId: "org_1",
    provider: "gmail",
    slug: "accounts",
    emailAddress: "accounts@acmecorp.com",
    displayName: "Accounts",
    status: "reconnect_required",
    lastSyncAt: "2026-05-07T09:15:00Z",
    lastSyncError: "OAuth token expired. Reconnect required.",
    lastSyncErrorCategory: "auth_expired",
    unreadCount: 0,
    inboxCount: 0,
  },
];

export const GLOBAL_SMART_VIEWS: MailboxTreeItem[] = [
  {
    id: "all-inboxes",
    label: "All Inboxes",
    href: "/app/mailbox",
    icon: "Inbox",
    unreadCount: 20,
    isSmartView: true,
  },
  {
    id: "unread",
    label: "Unread",
    href: "/app/mailbox/unread",
    icon: "Circle",
    unreadCount: 20,
    isSmartView: true,
  },
  {
    id: "assigned-to-me",
    label: "Assigned to me",
    href: "/app/mailbox/assigned",
    icon: "UserCheck",
    unreadCount: 3,
    isSmartView: true,
  },
  {
    id: "unassigned",
    label: "Unassigned",
    href: "/app/mailbox/unassigned",
    icon: "UserX",
    unreadCount: 8,
    isSmartView: true,
  },
  {
    id: "flagged",
    label: "Flagged",
    href: "/app/mailbox/flagged",
    icon: "Flag",
    unreadCount: 2,
    isSmartView: true,
  },
  {
    id: "waiting",
    label: "Waiting",
    href: "/app/mailbox/waiting",
    icon: "Clock",
    isSmartView: true,
  },
  {
    id: "linked",
    label: "Linked",
    href: "/app/mailbox/linked",
    icon: "Link2",
    isSmartView: true,
  },
  {
    id: "unlinked",
    label: "Unlinked",
    href: "/app/mailbox/unlinked",
    icon: "Link2Off",
    isSmartView: true,
  },
];

function mailboxFolders(connectionId: string, prefix: string): MailboxTreeItem[] {
  return [
    {
      id: `${connectionId}-inbox`,
      label: "Inbox",
      href: `/app/mailbox/${prefix}/inbox`,
      icon: "Inbox",
      mailboxConnectionId: connectionId,
    },
    {
      id: `${connectionId}-sent`,
      label: "Sent",
      href: `/app/mailbox/${prefix}/sent`,
      icon: "Send",
      mailboxConnectionId: connectionId,
    },
    {
      id: `${connectionId}-drafts`,
      label: "Drafts",
      href: `/app/mailbox/${prefix}/drafts`,
      icon: "FileEdit",
      mailboxConnectionId: connectionId,
    },
    {
      id: `${connectionId}-archive`,
      label: "Archive",
      href: `/app/mailbox/${prefix}/archive`,
      icon: "Archive",
      mailboxConnectionId: connectionId,
    },
    {
      id: `${connectionId}-spam`,
      label: "Spam",
      href: `/app/mailbox/${prefix}/spam`,
      icon: "ShieldAlert",
      mailboxConnectionId: connectionId,
    },
  ];
}

export const MOCK_MAILBOX_GROUPS: MailboxGroup[] = MOCK_CONNECTIONS.map((conn) => ({
  connection: conn,
  items: mailboxFolders(conn.id, conn.slug),
}));

// ─── Sprint 1.2: Thread detail mock data ────────────────────────────────────

export const MOCK_THREAD_DETAILS: Record<string, MailboxThreadDetail> = {
  t1: {
    threadId: "t1",
    mailboxConnectionId: "conn_billing",
    subject: "Invoice #INV-2026-0412 — Payment overdue",
    status: "open",
    assignee: "You",
    mailboxLabel: "Billing",
    mailboxColor: "#16294D",
    participantsSummary: "Priya Sharma, you",
    totalAttachments: 1,
    messages: [
      {
        id: "m1a",
        threadId: "t1",
        direction: "outbound",
        from: "Billing Team",
        fromInitial: "B",
        fromColor: "#16294D",
        fromEmail: "billing@acmecorp.com",
        to: ["priya.sharma@clientco.in"],
        subject: "Invoice #INV-2026-0412 — Payment overdue",
        bodyHtml: `<p>Dear Priya,</p><p>This is a reminder that Invoice <strong>#INV-2026-0412</strong> for ₹48,500 was due on <strong>30 April 2026</strong> and remains unpaid.</p><p>Please arrange payment at your earliest convenience. You can view and pay the invoice using the link below.</p><p>If you have already made the payment, please disregard this message and share the payment confirmation.</p><p>Regards,<br/>Billing Team<br/>Acme Corp</p>`,
        sentAt: "2026-05-06T09:00:00Z",
        isCollapsed: true,
        attachments: [
          { id: "att1", filename: "INV-2026-0412.pdf", mimeType: "application/pdf", sizeLabel: "142 KB" },
        ],
      },
      {
        id: "m1b",
        threadId: "t1",
        direction: "inbound",
        from: "Priya Sharma",
        fromInitial: "P",
        fromColor: "#7C3AED",
        fromEmail: "priya.sharma@clientco.in",
        to: ["billing@acmecorp.com"],
        subject: "Re: Invoice #INV-2026-0412 — Payment overdue",
        bodyHtml: `<p>Hi,</p><p>I wanted to follow up on the invoice we sent last week. Could you confirm the payment status? Our finance team is asking for an update.</p><p>Also, could you resend the invoice PDF? I seem to have misplaced the original.</p><p>Thanks,<br/>Priya</p>`,
        sentAt: "2026-05-08T10:42:00Z",
        isCollapsed: false,
        attachments: [],
      },
    ],
  },
  t2: {
    threadId: "t2",
    mailboxConnectionId: "conn_billing",
    subject: "Re: Quote QT-2026-0089 — Revised pricing",
    status: "open",
    assignee: null,
    mailboxLabel: "Billing",
    mailboxColor: "#16294D",
    participantsSummary: "Arjun Mehta, you",
    totalAttachments: 2,
    messages: [
      {
        id: "m2a",
        threadId: "t2",
        direction: "outbound",
        from: "Billing Team",
        fromInitial: "B",
        fromColor: "#16294D",
        fromEmail: "billing@acmecorp.com",
        to: ["arjun.mehta@techventures.io"],
        subject: "Quote QT-2026-0089 — Revised pricing",
        bodyHtml: `<p>Dear Arjun,</p><p>Please find attached the revised quote <strong>QT-2026-0089</strong> reflecting the updated pricing we discussed on our call.</p><p>The quote is valid until <strong>31 May 2026</strong>. Please let us know if you have any questions.</p><p>Best regards,<br/>Billing Team</p>`,
        sentAt: "2026-05-07T14:30:00Z",
        isCollapsed: true,
        attachments: [
          { id: "att2a", filename: "QT-2026-0089-revised.pdf", mimeType: "application/pdf", sizeLabel: "98 KB" },
          { id: "att2b", filename: "pricing-breakdown.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeLabel: "34 KB" },
        ],
      },
      {
        id: "m2b",
        threadId: "t2",
        direction: "inbound",
        from: "Arjun Mehta",
        fromInitial: "A",
        fromColor: "#0891B2",
        fromEmail: "arjun.mehta@techventures.io",
        to: ["billing@acmecorp.com"],
        subject: "Re: Quote QT-2026-0089 — Revised pricing",
        bodyHtml: `<p>Hi,</p><p>Thanks for the revised quote. We've reviewed it internally and have a few questions before we proceed:</p><ol><li>Can the implementation timeline be moved up by two weeks?</li><li>Is there flexibility on the annual support pricing?</li><li>Do you offer a multi-year discount?</li></ol><p>Looking forward to your response.</p><p>Best,<br/>Arjun</p>`,
        sentAt: "2026-05-08T09:15:00Z",
        isCollapsed: false,
        attachments: [],
      },
    ],
  },
  t3: {
    threadId: "t3",
    mailboxConnectionId: "conn_accounts",
    subject: "Voucher VCH-2026-0031 — Approval needed",
    status: "pending",
    assignee: null,
    mailboxLabel: "Accounts",
    mailboxColor: "#D97706",
    participantsSummary: "Neha Kapoor",
    totalAttachments: 1,
    messages: [
      {
        id: "m3a",
        threadId: "t3",
        direction: "inbound",
        from: "Neha Kapoor",
        fromInitial: "N",
        fromColor: "#C05092",
        fromEmail: "neha.kapoor@vendor.com",
        to: ["accounts@acmecorp.com"],
        subject: "Voucher VCH-2026-0031 — Approval needed",
        bodyHtml: `<p>Dear Team,</p><p>Please find attached the voucher <strong>VCH-2026-0031</strong> for the March services rendered. The total amount is ₹22,000.</p><p>Kindly approve at your earliest convenience so we can process the payment.</p><p>Regards,<br/>Neha Kapoor<br/>Vendor Services</p>`,
        sentAt: "2026-05-07T11:00:00Z",
        isCollapsed: false,
        attachments: [
          { id: "att3", filename: "VCH-2026-0031.pdf", mimeType: "application/pdf", sizeLabel: "88 KB" },
        ],
      },
    ],
  },
  t4: {
    threadId: "t4",
    mailboxConnectionId: "conn_billing",
    subject: "Statement of account — April 2026",
    status: "open",
    assignee: "Meera",
    mailboxLabel: "Billing",
    mailboxColor: "#16294D",
    participantsSummary: "Ravi Nair, Meera",
    totalAttachments: 1,
    messages: [
      {
        id: "m4a",
        threadId: "t4",
        direction: "inbound",
        from: "Ravi Nair",
        fromInitial: "R",
        fromColor: "#16A34A",
        fromEmail: "ravi.nair@globalretail.com",
        to: ["billing@acmecorp.com"],
        subject: "Statement of account — April 2026",
        bodyHtml: `<p>Hi,</p><p>Please find the attached statement of account for April 2026. The closing balance is ₹1,24,500.</p><p>Let us know if you have any queries or discrepancies to report.</p><p>Thanks,<br/>Ravi Nair<br/>Global Retail Ltd</p>`,
        sentAt: "2026-05-07T16:45:00Z",
        isCollapsed: false,
        attachments: [
          { id: "att4", filename: "statement-april-2026.pdf", mimeType: "application/pdf", sizeLabel: "210 KB" },
        ],
      },
    ],
  },
  t5: {
    threadId: "t5",
    mailboxConnectionId: "conn_support",
    subject: "Support: Unable to download invoice PDF",
    status: "open",
    assignee: null,
    mailboxLabel: "Support",
    mailboxColor: "#2563EB",
    participantsSummary: "Sunita Rao",
    totalAttachments: 0,
    messages: [
      {
        id: "m5a",
        threadId: "t5",
        direction: "inbound",
        from: "Sunita Rao",
        fromInitial: "S",
        fromColor: "#DC2626",
        fromEmail: "sunita.rao@customer.com",
        to: ["support@acmecorp.com"],
        subject: "Support: Unable to download invoice PDF",
        bodyHtml: `<p>Hi team,</p><p>I'm trying to download the invoice PDF from the customer portal but keep getting an error message: <em>"File not found"</em>.</p><p>This is for Invoice #INV-2026-0389. I need it urgently for our audit.</p><p>Can you help?</p><p>Thanks,<br/>Sunita</p>`,
        sentAt: "2026-05-07T08:30:00Z",
        isCollapsed: false,
        attachments: [],
      },
    ],
  },
  t6: {
    threadId: "t6",
    mailboxConnectionId: "conn_accounts",
    subject: "Re: TDS certificate for FY 2025-26",
    status: "closed",
    assignee: null,
    mailboxLabel: "Accounts",
    mailboxColor: "#D97706",
    participantsSummary: "Vikram Joshi, you",
    totalAttachments: 1,
    messages: [
      {
        id: "m6a",
        threadId: "t6",
        direction: "inbound",
        from: "Vikram Joshi",
        fromInitial: "V",
        fromColor: "#64748B",
        fromEmail: "vikram.joshi@enterprise.com",
        to: ["accounts@acmecorp.com"],
        subject: "TDS certificate for FY 2025-26",
        bodyHtml: `<p>Hi,</p><p>Could you please share the TDS certificate for FY 2025-26? We need it for our tax filing.</p><p>Thanks,<br/>Vikram</p>`,
        sentAt: "2026-05-05T10:00:00Z",
        isCollapsed: true,
        attachments: [],
      },
      {
        id: "m6b",
        threadId: "t6",
        direction: "outbound",
        from: "Accounts Team",
        fromInitial: "A",
        fromColor: "#D97706",
        fromEmail: "accounts@acmecorp.com",
        to: ["vikram.joshi@enterprise.com"],
        subject: "Re: TDS certificate for FY 2025-26",
        bodyHtml: `<p>Dear Vikram,</p><p>We've processed the TDS certificate for FY 2025-26. Please find it attached.</p><p>Let us know if you need any corrections.</p><p>Regards,<br/>Accounts Team</p>`,
        sentAt: "2026-05-06T14:20:00Z",
        isCollapsed: false,
        attachments: [
          { id: "att6", filename: "TDS-Certificate-FY2025-26.pdf", mimeType: "application/pdf", sizeLabel: "56 KB" },
        ],
      },
    ],
  },
};

// ─── Sprint 1.4: Admin / permission mock data ────────────────────────────────

const MOCK_POLICIES: Record<string, MailboxPermissionPolicy> = {
  conn_billing: {
    connectionId: "conn_billing",
    readAccess: "all_members",
    sendAccess: "all_members",
    manageAccess: "org_admins_only",
    accessSummary: "All members can read and reply",
  },
  conn_support: {
    connectionId: "conn_support",
    readAccess: "all_members",
    sendAccess: "specific_roles",
    manageAccess: "org_admins_only",
    accessSummary: "All members can read · Specific roles can reply",
  },
  conn_accounts: {
    connectionId: "conn_accounts",
    readAccess: "org_admins_only",
    sendAccess: "org_admins_only",
    manageAccess: "org_admins_only",
    accessSummary: "Admins only",
  },
};

export const MOCK_ADMIN_SUMMARIES: MailboxAdminSummary[] = MOCK_CONNECTIONS.map((conn) => ({
  connection: conn,
  policy: MOCK_POLICIES[conn.id],
  lastAdminActionAt: conn.status === "reconnect_required" ? "2026-05-07T09:15:00Z" : "2026-05-08T14:30:00Z",
  connectedBy: "Rahul Verma (Admin)",
}));

// ─── Sprint 1.5: Linked context mock data ────────────────────────────────────

import type { LinkedContextState, SmartViewDef } from "./types";

export const MOCK_LINKED_CONTEXT: Record<string, LinkedContextState> = {
  t1: {
    threadId: "t1",
    links: [
      {
        id: "lnk_t1_inv",
        threadId: "t1",
        entityType: "invoice",
        entityId: "inv_412",
        entityLabel: "Invoice #INV-2026-0412",
        entityRef: "INV-2026-0412",
        entityMeta: "₹48,500 · Due 30 Apr 2026",
        confidence: "confirmed",
        isPrimary: true,
      },
      {
        id: "lnk_t1_cust",
        threadId: "t1",
        entityType: "customer",
        entityId: "cust_priya",
        entityLabel: "Priya Sharma / ClientCo",
        entityRef: "CUST-0091",
        entityMeta: "Mumbai · Active",
        confidence: "confirmed",
        isPrimary: false,
      },
    ],
    suggestions: [],
    assignee: "You",
    status: "open",
    statusChangedAt: "2026-05-06T09:00:00Z",
    internalNote: "",
  },
  t2: {
    threadId: "t2",
    links: [
      {
        id: "lnk_t2_quote",
        threadId: "t2",
        entityType: "quote",
        entityId: "qt_089",
        entityLabel: "Quote QT-2026-0089",
        entityRef: "QT-2026-0089",
        entityMeta: "₹1,20,000 · Valid until 31 May",
        confidence: "confirmed",
        isPrimary: true,
      },
    ],
    suggestions: [
      {
        id: "sug_t2_cust",
        threadId: "t2",
        entityType: "customer",
        entityId: "cust_arjun",
        entityLabel: "Arjun Mehta / TechVentures",
        entityRef: "CUST-0047",
        entityMeta: "Bangalore · Active",
        confidence: "suggested",
        isPrimary: false,
      },
    ],
    assignee: null,
    status: "open",
    statusChangedAt: "2026-05-07T14:30:00Z",
    internalNote: "",
  },
  t3: {
    threadId: "t3",
    links: [
      {
        id: "lnk_t3_vch",
        threadId: "t3",
        entityType: "voucher",
        entityId: "vch_031",
        entityLabel: "Voucher VCH-2026-0031",
        entityRef: "VCH-2026-0031",
        entityMeta: "₹22,000 · Pending approval",
        confidence: "confirmed",
        isPrimary: true,
      },
    ],
    suggestions: [],
    assignee: null,
    status: "pending",
    statusChangedAt: "2026-05-07T11:00:00Z",
    internalNote: "Waiting for finance team sign-off.",
  },
  t4: {
    threadId: "t4",
    links: [],
    suggestions: [
      {
        id: "sug_t4_cust",
        threadId: "t4",
        entityType: "customer",
        entityId: "cust_ravi",
        entityLabel: "Ravi Nair / Global Retail",
        entityRef: "CUST-0012",
        entityMeta: "Chennai · Active",
        confidence: "suggested",
        isPrimary: false,
      },
    ],
    assignee: "Meera",
    status: "open",
    statusChangedAt: "2026-05-07T16:45:00Z",
    internalNote: "",
  },
  t5: {
    threadId: "t5",
    links: [],
    suggestions: [],
    assignee: null,
    status: "open",
    statusChangedAt: "2026-05-07T08:30:00Z",
    internalNote: "",
  },
  t6: {
    threadId: "t6",
    links: [
      {
        id: "lnk_t6_cust",
        threadId: "t6",
        entityType: "customer",
        entityId: "cust_vikram",
        entityLabel: "Vikram Joshi / Enterprise Ltd",
        entityRef: "CUST-0033",
        entityMeta: "Delhi · Active",
        confidence: "confirmed",
        isPrimary: true,
      },
    ],
    suggestions: [],
    assignee: null,
    status: "closed",
    statusChangedAt: "2026-05-06T14:20:00Z",
    internalNote: "TDS certificate issued and confirmed.",
  },
};

/** API-shaped mock threads for Sprint 4.1+ real-data tests. */
export const MOCK_API_THREADS = [
  {
    id: "t1",
    mailboxConnectionId: "conn_billing",
    providerThreadId: "gmail-t1",
    subject: "Invoice #INV-2026-0412 — Payment overdue",
    participants: [{ email: "priya@clientco.in", displayName: "Priya Sharma" }],
    lastMessageAt: "2026-05-08T10:42:00Z",
    unreadCount: 1,
    status: "OPEN" as const,
    assigneeId: "user-1",
    isFlagged: true,
    previewSnippet: "Hi, I wanted to follow up on the invoice we sent last week. Could you confirm the payment status?",
    attachmentCount: 0,
    createdAt: "2026-05-06T09:00:00Z",
    updatedAt: "2026-05-08T10:42:00Z",
  },
  {
    id: "t2",
    mailboxConnectionId: "conn_billing",
    providerThreadId: "gmail-t2",
    subject: "Re: Quote QT-2026-0089 — Revised pricing",
    participants: [{ email: "arjun@techventures.io", displayName: "Arjun Mehta" }],
    lastMessageAt: "2026-05-08T09:15:00Z",
    unreadCount: 1,
    status: "OPEN" as const,
    assigneeId: null,
    isFlagged: false,
    previewSnippet: "Thanks for the revised quote. We've reviewed it internally and have a few questions before we proceed.",
    attachmentCount: 2,
    createdAt: "2026-05-07T14:30:00Z",
    updatedAt: "2026-05-08T09:15:00Z",
  },
  {
    id: "t3",
    mailboxConnectionId: "conn_accounts",
    providerThreadId: "gmail-t3",
    subject: "Voucher VCH-2026-0031 — Approval needed",
    participants: [{ email: "neha@vendor.com", displayName: "Neha Kapoor" }],
    lastMessageAt: "2026-05-07T11:00:00Z",
    unreadCount: 0,
    status: "PENDING" as const,
    assigneeId: null,
    isFlagged: false,
    previewSnippet: "Please find attached the voucher for the March services. Kindly approve at your earliest convenience.",
    attachmentCount: 1,
    createdAt: "2026-05-07T11:00:00Z",
    updatedAt: "2026-05-07T11:00:00Z",
  },
  {
    id: "t4",
    mailboxConnectionId: "conn_billing",
    providerThreadId: "gmail-t4",
    subject: "Statement of account — April 2026",
    participants: [{ email: "ravi@globalretail.com", displayName: "Ravi Nair" }],
    lastMessageAt: "2026-05-07T16:45:00Z",
    unreadCount: 0,
    status: "OPEN" as const,
    assigneeId: "user-2",
    isFlagged: false,
    previewSnippet: "Please find the attached statement of account for April 2026. Let us know if you have any queries.",
    attachmentCount: 1,
    createdAt: "2026-05-07T16:45:00Z",
    updatedAt: "2026-05-07T16:45:00Z",
  },
  {
    id: "t5",
    mailboxConnectionId: "conn_support",
    providerThreadId: "gmail-t5",
    subject: "Support: Unable to download invoice PDF",
    participants: [{ email: "sunita@customer.com", displayName: "Sunita Rao" }],
    lastMessageAt: "2026-05-07T08:30:00Z",
    unreadCount: 1,
    status: "OPEN" as const,
    assigneeId: null,
    isFlagged: false,
    previewSnippet: "Hi team, I'm trying to download the invoice PDF from the portal but keep getting an error. Can you help?",
    attachmentCount: 0,
    createdAt: "2026-05-07T08:30:00Z",
    updatedAt: "2026-05-07T08:30:00Z",
  },
  {
    id: "t6",
    mailboxConnectionId: "conn_accounts",
    providerThreadId: "gmail-t6",
    subject: "Re: TDS certificate for FY 2025-26",
    participants: [{ email: "vikram@enterprise.com", displayName: "Vikram Joshi" }],
    lastMessageAt: "2026-05-06T14:20:00Z",
    unreadCount: 0,
    status: "CLOSED" as const,
    assigneeId: null,
    isFlagged: false,
    previewSnippet: "We've processed the TDS certificate. Please find it attached. Let us know if you need any corrections.",
    attachmentCount: 1,
    createdAt: "2026-05-05T10:00:00Z",
    updatedAt: "2026-05-06T14:20:00Z",
  },
];

export const SMART_VIEW_DEFS: SmartViewDef[] = [
  {
    id: "all-inboxes",
    label: "All Inboxes",
    href: "/app/mailbox",
    description: "All threads across connected mailboxes",
  },
  {
    id: "unread",
    label: "Unread",
    href: "/app/mailbox/unread",
    description: "Threads with unread messages",
  },
  {
    id: "assigned-to-me",
    label: "Assigned to me",
    href: "/app/mailbox/assigned",
    description: "Threads assigned to you",
  },
  {
    id: "unassigned",
    label: "Unassigned",
    href: "/app/mailbox/unassigned",
    description: "Threads with no assignee",
  },
  {
    id: "flagged",
    label: "Flagged",
    href: "/app/mailbox/flagged",
    description: "Threads you have flagged for follow-up",
  },
  {
    id: "waiting",
    label: "Waiting",
    href: "/app/mailbox/waiting",
    description: "Threads in pending / waiting state",
  },
  {
    id: "linked",
    label: "Linked",
    href: "/app/mailbox/linked",
    description: "Threads linked to a Slipwise record",
  },
  {
    id: "unlinked",
    label: "Unlinked",
    href: "/app/mailbox/unlinked",
    description: "Threads with no linked record",
  },
];
