import type { LucideIcon } from "lucide-react";
import {
  Home,
  FileText,
  Database,
  CreditCard,
  BookOpen,
  Workflow,
  BarChart3,
  Package,
  ShoppingCart,
  ShieldCheck,
  Users,
  BookMarked,
  ImageIcon,
  Receipt,
  Handshake,
  Inbox,
  MessagesSquare,
} from "lucide-react";

export interface NavItem {
  href: string;
  label: string;
  suite: string;
  badge?: string;
  icon?: LucideIcon;
  children?: { href: string; label: string }[];
}

export const suiteNavItems: NavItem[] = [
  {
    href: "/app/home",
    label: "Home",
    suite: "home",
    icon: Home,
  },
  {
    href: "/app/mailbox",
    label: "Mailbox",
    suite: "mailbox",
    icon: Inbox,
  },
  {
    href: "/app/messaging",
    label: "Messaging",
    suite: "messaging",
    icon: MessagesSquare,
  },
  {
    href: "/app/docs",
    label: "Docs",
    suite: "docs",
    icon: FileText,
    children: [
      { href: "/app/docs/invoices/new", label: "Invoice Studio" },
      { href: "/app/docs/vouchers/new", label: "Voucher Studio" },
      { href: "/app/docs/salary-slips/new", label: "Salary Slips" },
      { href: "/app/docs/invoices", label: "Invoice Vault" },
      { href: "/app/docs/vouchers", label: "Voucher Vault" },
      { href: "/app/docs/templates", label: "Templates" },
      { href: "/app/docs/templates/marketplace", label: "Template Marketplace" },
      { href: "/app/docs/templates/publisher/payouts", label: "Publisher Payouts" },
      { href: "/app/docs/pdf-studio", label: "PDF Studio" },
      { href: "/app/settings/sequences/history", label: "Sequence History" },
    ],
  },
  {
    href: "/app/data",
    label: "Data",
    suite: "data",
    icon: Database,
    children: [
      { href: "/app/data/vendors", label: "Vendors" },
      { href: "/app/data/employees", label: "Employees" },
      { href: "/app/data/salary-presets", label: "Salary Presets" },
    ],
  },
  {
    href: "/app/pay",
    label: "Pay",
    suite: "pay",
    icon: CreditCard,
    children: [
      { href: "/app/pay/receivables", label: "Receivables" },
      { href: "/app/pay/proofs", label: "Payment Proofs" },
      { href: "/app/pay/send-log", label: "Send Log" },
      { href: "/app/pay/recurring", label: "Recurring Invoices" },
      { href: "/app/pay/virtual-accounts", label: "Virtual Accounts" },
      { href: "/app/pay/unmatched", label: "Unmatched Payments" },
      { href: "/app/pay/reconciliation", label: "Bank Reconciliation" },
      { href: "/app/pay/collections-intelligence", label: "Collections Intelligence" },
      { href: "/app/pay/payroll", label: "Payroll Runs" },
    ],
  },
  {
    href: "/app/books",
    label: "Books",
    suite: "books",
    icon: BookOpen,
    children: [
      { href: "/app/books", label: "Overview" },
      { href: "/app/books/chart-of-accounts", label: "Chart of Accounts" },
      { href: "/app/books/journals", label: "Journals" },
      { href: "/app/books/ledger", label: "Ledger" },
      { href: "/app/books/trial-balance", label: "Trial Balance" },
      { href: "/app/books/banks", label: "Banks" },
      { href: "/app/books/reconciliation", label: "Reconciliation" },
      { href: "/app/books/reconciliation/workbench", label: "Workbench" },
      { href: "/app/books/reconciliation/cash-position", label: "Cash Position" },
      { href: "/app/books/vendor-bills", label: "Vendor Bills" },
      { href: "/app/books/payment-runs", label: "Payment Runs" },
      { href: "/app/books/close", label: "Close Center" },
      { href: "/app/books/reports/profit-loss", label: "Profit & Loss" },
      { href: "/app/books/reports/balance-sheet", label: "Balance Sheet" },
      { href: "/app/books/reports/cash-flow", label: "Cash Flow" },
      { href: "/app/books/reports/ar-aging", label: "AR Aging" },
      { href: "/app/books/reports/ap-aging", label: "AP Aging" },
      { href: "/app/books/inter-company", label: "Inter-Company Transfers" },
      { href: "/app/books/settings", label: "Settings" },
    ],
  },
  {
    href: "/app/flow",
    label: "Flow",
    suite: "flow",
    icon: Workflow,
    children: [
      { href: "/app/flow/tickets", label: "Tickets" },
      { href: "/app/flow/approvals", label: "Approvals" },
      { href: "/app/flow/notifications", label: "Notifications" },
      { href: "/app/flow/activity", label: "Activity Feed" },
      { href: "/app/flow/jobs", label: "Job Log" },
      { href: "/app/flow/workflows", label: "Automations" },
    ],
  },
  {
    href: "/app/intel",
    label: "Intel",
    suite: "intel",
    icon: BarChart3,
    children: [
      { href: "/app/intel/dashboard", label: "Dashboard" },
      { href: "/app/intel/reports", label: "Reports" },
      { href: "/app/intel/insights", label: "Insights" },
      { href: "/app/intel/anomalies", label: "Anomaly Detection" },
      { href: "/app/intel/document-intelligence", label: "Document Intelligence" },
      { href: "/app/intel/customer-health", label: "Customer Health" },
      { href: "/app/intel/collections", label: "Collections Queue" },
      { href: "/app/intel/gst-reports", label: "GST Reports" },
      { href: "/app/intel/gst-filings", label: "GST Filings" },
      { href: "/app/intel/consolidation", label: "Consolidated Reports" },
      { href: "/app/intel/forecast", label: "AI Forecast" },
      { href: "/app/intel/optimizer", label: "Cash Optimizer" },
      { href: "/app/intel/executive", label: "Executive Hub" },
      { href: "/app/intel/ai-usage", label: "AI Governance" },
    ],
  },
  {
    href: "/app/inventory/items",
    label: "Inventory",
    suite: "inventory",
    icon: Package,
    children: [
      { href: "/app/inventory/items", label: "Items" },
      { href: "/app/inventory/warehouses", label: "Warehouses" },
      { href: "/app/inventory/adjustments", label: "Adjustments" },
      { href: "/app/inventory/transfers", label: "Transfers" },
    ],
  },
  {
    href: "/app/procurement/po",
    label: "Procurement",
    suite: "procurement",
    icon: ShoppingCart,
    children: [
      { href: "/app/procurement/po", label: "Purchase Orders" },
      { href: "/app/procurement/grn", label: "Goods Receipts" },
      { href: "/app/procurement/bills", label: "Vendor Bills (AP)" },
    ],
  },
  {
    href: "/app/compliance",
    label: "Compliance",
    suite: "compliance",
    icon: ShieldCheck,
    children: [
      { href: "/app/compliance", label: "Overview" },
      { href: "/app/compliance/global", label: "Global Tax Engine" },
      { href: "/app/compliance/gst/reconciliation", label: "GSTR-2B Reconciliation" },
      { href: "/app/compliance/einvoice", label: "E-Invoice (IRN)" },
      { href: "/app/compliance/tds", label: "TDS Ledger" },
      { href: "/app/settings/compliance/einvoice", label: "E-Invoice Config" },
      { href: "/app/admin/audit/integrity", label: "Audit Integrity" },
    ],
  },
  {
    href: "/app/clients",
    label: "Clients",
    suite: "clients",
    icon: Users,
    children: [
      { href: "/app/clients", label: "Workspace" },
    ],
  },
  {
    href: "/app/crm",
    label: "CRM",
    suite: "crm",
    icon: Users,
    children: [
      { href: "/app/crm", label: "Dashboard" },
      { href: "/app/crm/vendors", label: "Vendors" },
    ],
  },
  {
    href: "/app/sop",
    label: "Knowledge Base",
    suite: "sop",
    icon: BookMarked,
    children: [
      { href: "/app/sop", label: "All SOPs" },
      { href: "/app/sop/new", label: "+ New SOP" },
    ],
  },
  {
    href: "/app/pixel",
    label: "Pixel",
    suite: "pixel",
    icon: ImageIcon,
    children: [
      { href: "/app/pixel/passport", label: "Passport Photo" },
      { href: "/app/pixel/resize", label: "Resize & Compress" },
      { href: "/app/pixel/adjust", label: "Adjustments" },
      { href: "/app/pixel/print-layout", label: "Print Layout" },
      { href: "/app/pixel/label", label: "Labels" },
    ],
  },
  {
    href: "/app/billing",
    label: "Billing",
    suite: "billing",
    icon: Receipt,
    children: [
      { href: "/app/billing", label: "Plan & Usage" },
      { href: "/app/billing/history", label: "Billing History" },
    ],
  },
  {
    href: "/app/partner",
    label: "Partner",
    suite: "partner",
    icon: Handshake,
    children: [
      { href: "/app/partner", label: "Dashboard" },
      { href: "/app/partner/clients", label: "Managed Clients" },
      { href: "/app/partner/reports", label: "Reports" },
      { href: "/app/partner/apply", label: "Apply" },
    ],
  },
];
