import type { BrandingConfig } from "@/lib/branding";

export type InvoiceTemplateId = "minimal" | "professional" | "bold-brand" | "classic-bordered" | "modern-edge";

export type InvoiceExportFormat = "pdf" | "png";

export type InvoiceLineItemFormValue = {
  description: string;
  inventoryItemId?: string;
  quantity: string;
  unitPrice: string;
  taxRate: string;
  discountAmount: string;
};

export type InvoiceVisibilityConfig = {
  showAddress: boolean;
  showEmail: boolean;
  showPhone: boolean;
  showWebsite: boolean;
  showBusinessTaxId: boolean;
  showClientAddress: boolean;
  showClientEmail: boolean;
  showClientPhone: boolean;
  showClientTaxId: boolean;
  showShippingAddress: boolean;
  showDueDate: boolean;
  showPlaceOfSupply: boolean;
  showNotes: boolean;
  showTerms: boolean;
  showBankDetails: boolean;
  showSignature: boolean;
  showPaymentSummary: boolean;
  showUpiDetails: boolean;
};

export type InvoiceFormValues = {
  templateId: InvoiceTemplateId;
  branding: BrandingConfig;
  website: string;
  businessTaxId: string;
  clientSalutation?: string;
  clientName: string;
  clientAddress: string;
  shippingAddress: string;
  clientEmail: string;
  clientPhone: string;
  clientTaxId: string;
  invoiceNumber?: string;
  invoiceDate: string;
  dueDate: string;
  placeOfSupply: string;
  extraCharges: string;
  invoiceLevelDiscount: string;
  amountPaid: string;
  notes: string;
  terms: string;
  bankName: string;
  bankAccountNumber: string;
  bankIfsc: string;
  upiId: string;
  upiQrDataUrl: string;
  authorizedBy: string;
  authorizedByDesignation?: string;
  authorizedByCompany?: string;
  lineItems: InvoiceLineItemFormValue[];
  visibility: InvoiceVisibilityConfig;
  tagIds?: string[];
};

export type InvoiceLineItem = {
  description: string;
  quantity: number;
  unitPrice: number;
  taxRate: number;
  discountAmount: number;
  baseAmount: number;
  taxableAmount: number;
  taxAmount: number;
  lineTotal: number;
  unitPriceFormatted: string;
  discountAmountFormatted: string;
  baseAmountFormatted: string;
  taxAmountFormatted: string;
  lineTotalFormatted: string;
};

export type InvoiceDocument = {
  templateId: InvoiceTemplateId;
  title: string;
  branding: BrandingConfig;
  website?: string;
  businessTaxId?: string;
  clientSalutation?: string;
  clientName: string;
  clientAddress?: string;
  shippingAddress?: string;
  clientEmail?: string;
  clientPhone?: string;
  clientTaxId?: string;
  invoiceNumber?: string;
  invoiceDate: string;
  dueDate?: string;
  placeOfSupply?: string;
  currencyCode: "INR";
  lineItems: InvoiceLineItem[];
  subtotal: number;
  totalDiscount: number;
  totalTax: number;
  extraCharges: number;
  invoiceLevelDiscount: number;
  grandTotal: number;
  amountPaid: number;
  balanceDue: number;
  subtotalFormatted: string;
  totalDiscountFormatted: string;
  totalTaxFormatted: string;
  extraChargesFormatted: string;
  invoiceLevelDiscountFormatted: string;
  grandTotalFormatted: string;
  amountPaidFormatted: string;
  balanceDueFormatted: string;
  amountInWords: string;
  notes?: string;
  terms?: string;
  bankName?: string;
  bankAccountNumber?: string;
  bankIfsc?: string;
  upiId?: string;
  upiQrDataUrl?: string;
  authorizedBy?: string;
  authorizedByDesignation?: string;
  authorizedByCompany?: string;
  visibility: InvoiceVisibilityConfig;
};
