"use client";

import { useState } from "react";
import { EditRecurringRuleModal } from "./edit-modal";
import { Pencil, ArrowLeft, Clock, Activity, CheckCircle, FileText } from "lucide-react";
import Link from "next/link";

function formatDate(date: Date | string | null) {
  if (!date) return "—";
  return new Date(date).toLocaleDateString("en-IN", {
    month: "short",
    day: "numeric",
    year: "numeric"
  });
}

export function RecurringRuleDetailClient({ rule }: { rule: any }) {
  const [isEditing, setIsEditing] = useState(false);

  return (
    <div className="mx-auto max-w-6xl p-6">
      <div className="mb-6">
        <Link href="/app/pay/recurring" className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900 transition-colors">
          <ArrowLeft className="h-4 w-4" />
          Back to Rules
        </Link>
      </div>

      <div className="mb-8 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900">
            Rule for {rule.baseInvoice.invoiceNumber}
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Generating invoices {rule.frequency.toLowerCase()} automatically.
          </p>
        </div>
        <button
          onClick={() => setIsEditing(true)}
          className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-900 shadow-sm transition-colors hover:bg-slate-50"
        >
          <Pencil className="h-4 w-4" />
          Edit Rule
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 text-slate-500 mb-2">
            <Activity className="h-5 w-5 text-red-500" />
            <span className="text-sm font-medium">Status</span>
          </div>
          <p className="text-xl font-bold text-slate-900">{rule.status}</p>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 text-slate-500 mb-2">
            <Clock className="h-5 w-5 text-amber-500" />
            <span className="text-sm font-medium">Next Run</span>
          </div>
          <p className="text-xl font-bold text-slate-900">{formatDate(rule.nextRunAt)}</p>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 text-slate-500 mb-2">
            <CheckCircle className="h-5 w-5 text-emerald-500" />
            <span className="text-sm font-medium">End Date</span>
          </div>
          <p className="text-xl font-bold text-slate-900">{formatDate(rule.endDate)}</p>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 text-slate-500 mb-2">
            <FileText className="h-5 w-5 text-blue-500" />
            <span className="text-sm font-medium">Generated</span>
          </div>
          <p className="text-xl font-bold text-slate-900">{rule.runsCount} Invoices</p>
        </div>
      </div>

      <div className="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden">
        <div className="border-b border-slate-200 bg-slate-50 px-6 py-4">
          <h2 className="text-lg font-semibold text-slate-900">Generated Invoices History</h2>
        </div>
        
        {rule.generatedInvoices.length === 0 ? (
          <div className="flex flex-col items-center justify-center p-12 text-center">
            <div className="mb-4 rounded-full bg-slate-50 p-4 ring-1 ring-slate-100">
              <Clock className="h-8 w-8 text-slate-400" />
            </div>
            <p className="text-sm text-slate-500">No invoices have been generated by this rule yet.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-slate-200">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-900">Date Generated</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-900">Invoice Number</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-900">Amount</th>
                  <th className="px-6 py-4 text-left text-xs font-semibold text-slate-900">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {rule.generatedInvoices.map((inv: any) => (
                  <tr key={inv.id} className="hover:bg-slate-50 transition-colors">
                    <td className="whitespace-nowrap px-6 py-4 text-sm text-slate-900">
                      {formatDate(inv.createdAt)}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-sm font-medium text-slate-900">
                      {inv.invoiceNumber || "Draft (Pending)"}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4 text-sm text-slate-600">
                      ₹{Number(inv.totalAmount).toLocaleString("en-IN")}
                    </td>
                    <td className="whitespace-nowrap px-6 py-4">
                      <span className="inline-flex items-center rounded-md bg-slate-100 px-2 py-1 text-xs font-medium text-slate-700 ring-1 ring-inset ring-slate-500/10">
                        {inv.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {isEditing && (
        <EditRecurringRuleModal rule={rule} onClose={() => setIsEditing(false)} />
      )}
    </div>
  );
}
